<%@ Page Title="Employee Listing" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EmployeeListing.aspx.cs" Inherits="GroupFinal.Views.EmployeeListing" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <div  class="empListing">
     <h2><%: Title %>  </h2>
         <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" Width="1138px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
             <AlternatingRowStyle BackColor="White" />
             <Columns>
                 <asp:CommandField ShowSelectButton="True" />
                 <asp:BoundField DataField="employeeFirst" HeaderText="First Name" SortExpression="employeeFirst" >
                 <HeaderStyle HorizontalAlign="Center" />
                 </asp:BoundField>
                 <asp:BoundField DataField="employeeLast" HeaderText="Last Name" SortExpression="employeeLast" />
                 <asp:BoundField DataField="employeeStatus" HeaderText="Status" SortExpression="employeeStatus" />
                 <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
                 <asp:BoundField DataField="storeNum" HeaderText="storeNum" SortExpression="storeNum" Visible="False" />
             </Columns>
             <EditRowStyle BackColor="#7C6F57" HorizontalAlign="Center" />
             <EmptyDataRowStyle HorizontalAlign="Center" />
             <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
             <HeaderStyle BackColor="#186818" Font-Bold="True" ForeColor="White" BorderStyle="Groove" HorizontalAlign="Right" VerticalAlign="Middle" />
             <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="#E3EAEB" HorizontalAlign="Center" />
             <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
             <SortedAscendingCellStyle BackColor="#F8FAFA" />
             <SortedAscendingHeaderStyle BackColor="#246B61" HorizontalAlign="Center" />
             <SortedDescendingCellStyle BackColor="#D4DFE1" />
             <SortedDescendingHeaderStyle BackColor="#15524A" HorizontalAlign="Center" />
         </asp:GridView>
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:OsheaDB2644ConnectionString %>" SelectCommand="SELECT [employeeFirst], [employeeLast], [employeeStatus], [Role], [storeNum] FROM [Employee]" OldValuesParameterFormatString="original_{0}"></asp:SqlDataSource>
    
    
</div>

   
</asp:Content>
